name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, curl, sqlite3
        coverage: none

    - name: Copy .env
      working-directory: ./weather-api
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Composer Dependencies
      working-directory: ./weather-api
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate Application Key
      working-directory: ./weather-api
      run: php artisan key:generate

    - name: Set Directory Permissions
      working-directory: ./weather-api
      run: chmod -R 777 storage bootstrap/cache

    - name: Create SQLite Database
      working-directory: ./weather-api
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Laravel Tests
      working-directory: ./weather-api
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
